spring.application.name=expense-intelligence-system
spring.datasource.url=jdbc:mysql://localhost:3306/expense_db
spring.datasource.username=root
spring.datasource.password=MySQL#2103H

spring.jpa.hibernate.ddl-auto=update